[project]
name = "uzum"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.46",
    "celery>=5.6.2",
    "django>=6.0.2",
    "django-celery-beat>=2.1.0",
    "django-jazzmin>=3.0.2",
    "django-location-field>=2.7.3",
    "django-minio-storage>=0.5.9",
    "django-mptt>=0.18.0",
    "django-rest-swagger>=2.2.0",
    "django-storages>=1.14.6",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "image>=1.5.33",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
